name: Fluxo padrão
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar a versão automática
      - name: Set build version
        id: version
        run: |
          # Definir a versão base
          BASE_VERSION="1.0.0"

          # Obter o número da execução
          BUILD_NUMBER=${{ github.run_number }}

          # Gerar a nova versão
          NEW_VERSION="$BASE_VERSION-$BUILD_NUMBER"

          # Exportar a versão como variável de ambiente
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "New version: $NEW_VERSION"

      # Instalar o .NET SDK para os testes
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Versão do .NET SDK

      # Restaurar dependências do .NET
      - name: Restore dependencies
        run: dotnet restore

      - name: Setup PowerShell
        run: |
          # Baixar e instalar PowerShell no Ubuntu
          wget -q "https://github.com/PowerShell/PowerShell/releases/download/v7.3.1/powershell-7.3.1-linux-x64.tar.gz"
          mkdir ~/powershell
          tar -xvf ./powershell-7.3.1-linux-x64.tar.gz -C ~/powershell
          sudo ln -s ~/powershell/pwsh /usr/local/bin/pwsh

      # Testar a conexão com o banco usando o script PowerShell
      - name: Execute PowerShell Script
        run: |
          pwsh ./path/to/your/script.ps1 -Instance ${{ secrets.DB_INSTANCE }} -DbName ${{ secrets.DB_NAME }} -UID ${{ secrets.DB_USER }} -Password ${{ secrets.DB_PASSWORD }}

      # Login no Docker
      - name: Docker Login 
        uses: docker/login-action@v3.0.0
        with:
          username: 'zennbyte'
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir e enviar a imagem Docker
      - name: Build and Push Docker images
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          tags: |
            zennbyte/api-contactmanager:${{ env.NEW_VERSION }}
          push: true
